'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { useStore } from '@/store/useStore'
import { injectCurvature } from './curveWorld'

/*
 * BuildingCloud — loads the pre-sampled building point data from
 * /building-points.json (generated by tools/sample-building.mjs) and renders
 * it as a coloured particle cloud.
 *
 * Coordinate conversion: the FBX uses Z-up, Three.js uses Y-up.
 * We rotate on load: THREE_Y = FBX_Z, THREE_Z = -FBX_Y.
 * The model is then centred on XZ and its base sits at Y = 0 (ground level).
 */
const REVEAL_START = 28     // above building top (~22 units)
const REVEAL_END   = -8
const REVEAL_DUR   = 3.8    // match terrain so both waves run together

export default function BuildingCloud({ position = [0, 0, 0] }) {
  const [data, setData]   = useState(null)
  const meshRef           = useRef()
  const revealStart       = useRef(null)
  const isExploring       = useStore(s => s.isExploring)

  useEffect(() => {
    fetch('/building-points.json')
      .then(r => r.json())
      .then(setData)
  }, [])

  const geometry = useMemo(() => {
    if (!data) return null

    const { positions: rawPos, colors: rawCol, bounds, count } = data

    /* --- coordinate conversion + centering + scale --- */
    /* After Z-up → Y-up: THREE_X=FBX_X, THREE_Y=FBX_Z, THREE_Z=-FBX_Y      */
    const cx     = (bounds.minX + bounds.maxX) / 2       // X centre (≈ 0)
    const cy     = bounds.minZ                            // base of building → sit at Y=0
    const cz     = -(bounds.minY + bounds.maxY) / 2      // Z centre after -FBX_Y flip

    const modelH = bounds.maxZ - bounds.minZ              // FBX Z range = building height
    const scale  = 22 / modelH                            // target: 22 units tall

    const pos = new Float32Array(count * 3)
    const col = new Float32Array(count * 3)
    const rnd = new Float32Array(count * 3)   // independent animation seeds

    for (let i = 0; i < count; i++) {
      const fx = rawPos[i * 3]
      const fy = rawPos[i * 3 + 1]
      const fz = rawPos[i * 3 + 2]

      pos[i * 3]     = (fx  - cx) * scale
      pos[i * 3 + 1] = (fz  - cy) * scale   /* FBX Z → THREE Y (height) */
      pos[i * 3 + 2] = (-fy - cz) * scale   /* -FBX Y → THREE Z (depth) */

      /* Scale down so additive blending doesn't saturate to white.
         The texture is neutral stone/beige — this keeps subtle variation visible. */
      col[i * 3]     = rawCol[i * 3]     * 0.65
      col[i * 3 + 1] = rawCol[i * 3 + 1] * 0.65
      col[i * 3 + 2] = rawCol[i * 3 + 2] * 0.65

      rnd[i * 3]     = Math.random()
      rnd[i * 3 + 1] = Math.random()
      rnd[i * 3 + 2] = Math.random()
    }

    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.BufferAttribute(pos, 3))
    geo.setAttribute('color',    new THREE.BufferAttribute(col, 3))
    geo.setAttribute('aRandVec', new THREE.BufferAttribute(rnd, 3))
    return geo
  }, [data])

  /*
   * Same independent per-point animation as the terrain but with a much
   * smaller amplitude so the building silhouette stays crisp.
   */
  const material = useMemo(() => {
    const mat = new THREE.PointsMaterial({
      size: 0.18,
      sizeAttenuation: true,
      vertexColors: true,
      transparent: true,
      alphaTest: 0.01,
      blending: THREE.AdditiveBlending,
      depthWrite: false,
    })

    mat.onBeforeCompile = (shader) => {
      shader.uniforms.uTime    = { value: 0 }
      shader.uniforms.uRevealY = { value: REVEAL_START }

      /* ── Vertex shader ──────────────────────────────────────────── */
      shader.vertexShader = shader.vertexShader.replace(
        'void main() {',
        `attribute vec3 aRandVec;
uniform float uTime;
varying float vWPosY;
void main() {`
      )

      shader.vertexShader = shader.vertexShader.replace(
        '#include <begin_vertex>',
        `#include <begin_vertex>
        float phX = aRandVec.x * 6.2832;
        float spX = 0.10 + aRandVec.x * 0.15;
        float amX = 0.015 + aRandVec.x * 0.025;
        transformed.x += sin(uTime * spX          + phX) * amX
                       + sin(uTime * spX * 1.6180 + phX * 1.7) * amX * 0.5;

        float phY = aRandVec.y * 6.2832;
        float spY = 0.10 + aRandVec.y * 0.15;
        float amY = 0.015 + aRandVec.y * 0.025;
        transformed.y += sin(uTime * spY          + phY) * amY
                       + sin(uTime * spY * 1.6180 + phY * 1.7) * amY * 0.5;

        float phZ = aRandVec.z * 6.2832;
        float spZ = 0.10 + aRandVec.z * 0.15;
        float amZ = 0.015 + aRandVec.z * 0.025;
        transformed.z += sin(uTime * spZ          + phZ) * amZ
                       + sin(uTime * spZ * 1.6180 + phZ * 1.7) * amZ * 0.5;

        vWPosY = transformed.y;`
      )

      /* ── Fragment shader ────────────────────────────────────────── */
      shader.fragmentShader = shader.fragmentShader.replace(
        'void main() {',
        `varying float vWPosY;
uniform float uRevealY;
void main() {`
      )

      shader.fragmentShader = shader.fragmentShader.replace(
        '#include <alphatest_fragment>',
        `float revealEdge   = 2.0;
        float revealFactor = smoothstep(uRevealY - revealEdge, uRevealY + revealEdge, vWPosY);
        diffuseColor.a    *= revealFactor;
        #include <alphatest_fragment>`
      )

      /* Spherical-world bend — keeps buildings sitting on the curved road */
      injectCurvature(shader)

      mat.userData.shader = shader
    }

    return mat
  }, [])

  useFrame(({ clock }) => {
    const shdr = material.userData.shader
    if (!shdr) return

    if (isExploring && revealStart.current === null) {
      revealStart.current = clock.elapsedTime
    }

    if (revealStart.current !== null) {
      const t        = clock.elapsedTime - revealStart.current
      const progress = Math.min(t / REVEAL_DUR, 1.0)
      const eased    = 1 - Math.pow(1 - progress, 3)
      shdr.uniforms.uRevealY.value = REVEAL_START + (REVEAL_END - REVEAL_START) * eased
    }

    shdr.uniforms.uTime.value = clock.elapsedTime
  })

  if (!geometry) return null

  return (
    <points
      ref={meshRef}
      geometry={geometry}
      material={material}
      /* Centred on XZ; negative Y sinks the base into average terrain level */
      position={position}
    />
  )
}
